### ISSUE TITLE
Auto hide of canvas controls causes lag

### ISSUE THREAD

**Issue by radpet** [ProjectMirador/mirador#993]
@rsinghal  @beaudet After upgrading to mirador 2.1 we experienced serious performance issue when we open more than one image in mirador. I checked out for memory leaks and it seems that there are nodes that are not garbage collected when switching between images. In my opinion the problems comes from the functionality that shows/hides the controls/arrows/hud when you focus/blur the viewer. We tested it versus an old version, few commits ahead the master branch, where there is not focus/blur listeners for the controls. You can compare the two results.

[Mirador lag_old2.webm.zip](https://github.com/IIIF/mirador/files/341268/Mirador.lag_old2.webm.zip)
[Mirador lag2.1.zip](https://github.com/IIIF/mirador/files/341260/Mirador.lag2.1.zip)

**Comment by rsinghal** [comment]
@radpet Yes, we have noticed lag with the auto hide functionality with the canvas controls.  We are going to temporarily disable them until we can improve that.  I will push through that change into `release2.1`

@aeschylus

**Comment by radpet** [comment]
@rsinghal Thank you very much, would you please sync the annotation-work branch after that with 2.1?

**Comment by beaudet** [comment]
would be great to get the annotation work branch merged

**Comment by rsinghal** [comment]
@radpet done

@beaudet I merged `annotation-work` into `release2.1` a couple of days ago, so those two are now aligned.

**Comment by radpet** [comment]
@rsinghal The hud is still showing/hiding in bookview. However we can stop it if you set  'autoHideControls' prop to false in the config

**Comment by rsinghal** [comment]
commented it out in BookView and merged the changes into `annotation-work`

**Comment by rsinghal** [comment]
Related to #386

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
